# -*- coding: utf-8 -*-
"""program_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABn3dfsstYh7p2ljsCb1q_4o1so1bpwx
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
    )

import matplotlib.pyplot as plt

df = pd.read_csv("studentt.csv")
print(df)

print(df.head())

print(df.info())

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True),inplace=True)

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True),inplace=True)

print(df.isnull().sum())

x=df[["age","studyhours","attendance","marks"]]

y=df['result']

encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

encoder.fit_transform(y)

x_train,x_test,y_train,y_test=train_test_split(
    x,y,
    test_size=0.2,
    random_state=42,
    stratify=y)

print("Training samples:",len(x_train))

print("teststing samples:",len(x_test))

model = DecisionTreeClassifier(random_state=42)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

print("actual:",y_test)
print("Predicted:",y_pred)

accuracy=accuracy_score(y_test,y_pred)

print("Accuracy:",accuracy)

precision =  precision_score(y_test,y_pred,zero_division=0)

print("precision:",precision)

recall = recall_score(y_test,y_pred,zero_division=0)

print("Recall:",recall)

f1=f1_score(y_test,y_pred,zero_division=0)
print("F1 Score:",f1)

cm = confusion_matrix(y_test,y_pred,labels=encoder.transform(encoder.classes_))

print("confusion matrix:")
print(cm)

disp=ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=encoder.classes_
)

disp.plot()
plt.title("Confusion Matrix")
plt.show()

